# On file change, update submodule of sigpwny/notes.sigpwny.com using a CI bot commit.
name: Sync notes changes to sigpwny/notes.sigpwny.com
on:
  push:
    paths:
      - '*/**'
      - '!./README.md'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  update:
    name: Update git submodule
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          repository: sigpwny/notes.sigpwny.com
          submodules: true
      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: Commit
        run: |
          git config user.email "hello@sigpwny.com"
          git config user.name "SIGPwny CI/CD"
          git add --all
          git commit -m "sync: sigpwny/notes" || echo "No changes to commit"
          git push
